# Generated by Django 5.0.1 on 2024-01-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='code',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
