# Generated by Django 5.0.1 on 2024-01-09 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_color_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='color',
        ),
        migrations.RemoveField(
            model_name='color',
            name='status',
        ),
    ]
