# Generated by Django 5.0.1 on 2024-01-09 05:10

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_remove_color_color_remove_color_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='code',
            new_name='status',
        ),
        migrations.AddField(
            model_name='color',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
    ]
