# Generated by Django 5.0.1 on 2024-01-10 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='status',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.color'),
        ),
    ]
