# Generated by Django 5.0.1 on 2024-01-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_alter_color_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
