# Generated by Django 5.0.1 on 2024-01-10 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_alter_color_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='status',
            new_name='name',
        ),
    ]
