# Generated by Django 5.0.1 on 2024-01-10 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_alter_color_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='color',
            new_name='background_color',
        ),
    ]
