# Generated by Django 5.0.1 on 2024-01-10 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_rename_color_product_background_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='background_color',
            new_name='color',
        ),
    ]
