# Generated by Django 5.0.1 on 2024-01-10 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_rename_background_color_product_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='name',
            new_name='status',
        ),
    ]
