# Generated by Django 5.0.1 on 2024-01-10 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_rename_name_color_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='color',
        ),
    ]
