# Generated by Django 5.0.1 on 2024-01-14 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_alter_productreview_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('process', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='processing', max_length=30),
        ),
        migrations.CreateModel(
            name='CartOrderProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=200)),
                ('product_status', models.CharField(max_length=200)),
                ('item', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('qty', models.IntegerField(default=0)),
                ('price', models.FloatField(default='1.99', max_length=99999999999)),
                ('total', models.FloatField(default='1.99', max_length=99999999999)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.cartorder')),
            ],
        ),
    ]
