# Generated by Django 5.0.1 on 2024-01-14 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0034_cartorder_product_status_cartorderproducts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorderproducts',
            old_name='price',
            new_name='item_price',
        ),
    ]
