# Generated by Django 5.0.1 on 2024-01-15 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0037_rename_wishlist_wishlist_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartOrderItems',
        ),
    ]
