# Generated by Django 5.0.1 on 2024-01-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0039_product_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
