# Generated by Django 5.0.1 on 2024-01-23 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0040_newslettersubscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorderproducts',
            old_name='qty',
            new_name='quantity',
        ),
        migrations.CreateModel(
            name='CartOrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.FloatField(default='1.99', max_length=99999999999)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.address')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.product')),
            ],
        ),
    ]
