# Generated by Django 5.0.1 on 2024-01-23 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0043_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.coupon'),
        ),
    ]
