# Generated by Django 5.0.1 on 2024-01-26 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0045_tag_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
